spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/paper?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
isolation:
    ssi: MsSsi
    rr: MsRr
    rc: MsRc
    ru: MsRu