server:
    port: 8888

spring:
    application:
        name: paper

    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/paper?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
