spring:
    datasource:
        username: dba
        password: 123456
        url: jdbc:mysql://localhost:3306/paper?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
isolation:
    ssi: MySsi
    rr: MyRr
    rc: MyRc
    ru: MyRu