spring:
    datasource:
        username: sa
        password: Winter2019
        url: jdbc:sqlserver://localhost:1433;DatabaseName=paper

#        username: mssql
#        password: 123qwe!@#
#        url: jdbc:sqlserver://rm-2zeewu126gdi11xj3.sqlserver.rds.aliyuncs.com:3433;DatabaseName=paper

        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

        initialSize: 1
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

isolation:
    ssi: MsSsi
    rr: MsRr
    rc: MsRc
    ru: MsRu