server:
    port: 8080

spring:
    redis:
        host: localhost
    redisson:
        enable: true
        singleServerConfig:
            idleConnectionTimeout: 10000
            pingTimeout: 1000
            connectTimeout: 10000
            timeout: 3000
            retryAttempts: 3
            retryInterval: 1500
            address: redis://localhost:6379

config:
    user-max: 3000
    cash-init: 10000
    credit-init: 20000
    product-max: 1000000
    product-stock-max: 500
    pool-size: 16