server:
    port: 8080

spring:
    redis:
        host: localhost

config:
    user-max: 3000
    cash-init: 10000
    credit-init: 20000
    product-max: 1000000
    product-stock-max: 500
    pool-size: 16