server:
    port: 8080

spring:
    redis:
        #        host: localhost
        host: r-el58c6fd73430944.redis.pcloud.citic.com
        password: r-el58c6fd73430944:AliOS1688
        database: 13
    redisson:
        enable: true
        singleServerConfig:
            idleConnectionTimeout: 10000
            pingTimeout: 1000
            connectTimeout: 10000
            timeout: 3000
            retryAttempts: 3
            retryInterval: 1500
            address: redis://localhost:6379

config:
    user-max: 3000
    cash-init: 100000000
    credit-init: 20000000
    product-max: 1000000
    product-stock-max: 1000000
    product-zipf: 1.3
    pool-size: 16
    batch-size: 10